config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/user-settings', to: 'pages#user_settings', as: 'user_settings'
  # get '/user_code', to: 'games#user_code', as: 'user_code'

  devise_scope :user do
    authenticated :user do
      get '/', to: 'pages#dashboard', as: 'authenticated_root'
    end
    unauthenticated do
      get '/', to: 'pages#home', as: 'unauthenticated_root'
    end
  end

  resources :challenges, only: %i[new create]
  resources :leagues, only: %i[index new create show]

  resources :users do
    resources :games, only: %i[new create]
    resources :game_rounds, only: %i[index]
    member do
      get :send_game_invitation
      post :send_invitation
      post :accept_invitation
      delete :reject_invitation
    end
  end

  resources :games, only: %i[show edit update] do
    member do
      post :round_won
      post :update_display
      post :user_code
      post :user_ready_next_round
      post :forfeit_round
      post :invite_response
      post :cancel_invite
      post :game_disconnected
      post :game_metadata
    end
    resources :game_rounds, only: %i[new create] do
      resources :challenges, only: %i[show]
    end
  end

  resources :game_rounds, only: %i[update]
end

app/models/league.rb
# frozen_string_literal: true

class League < ApplicationRecord
  has_many :user_leagues
  has_many :users, through: :user_leagues
  has_many :games

  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/leagues_controller.rb
# frozen_string_literal: true

class LeaguesController < ApplicationController
  before_action :add_requests, only: %i[index new show]

  def index
    @leagues = policy_scope(League)
    @leagues = current_user.leagues
  end

  def show
    @league = League.find(params[:id])

    authorize @league
  end

  def new
    @league = League.new

    authorize @league
  end

  def create
    @league = League.new(league_params)
    @league.save!
    user_league = UserLeague.new(league: @league, user: current_user)
    user_league.save!

    redirect_to leagues_path

    authorize @league
  end

  private

  def league_params
    params.require(:league).permit(:name)
  end

  def add_requests
    @requests = current_user.pending_invitations
  end
end

app/views/leagues/create.html.erb
<h1>Leagues#create</h1>
<p>Find me in app/views/leagues/create.html.erb</p>

app/views/leagues/index.html.erb
<h1>Leagues#index</h1>
<p>Find me in app/views/leagues/index.html.erb</p>
<% @leagues.each do |league| %>
  <p><%= link_to league.name, league_path(league) %></p>
<% end %>

<%= link_to "New League", new_league_path %>

app/views/leagues/new.html.erb
<h1>Leagues#new</h1>
<p>Find me in app/views/leagues/new.html.erb</p>

<%= simple_form_for @league do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/leagues/show.html.erb
<h1>Leagues#show</h1>
<p>Find me in app/views/leagues/show.html.erb</p>
<% @league.users.each do |user| %>
  <p style="color: white"><%= user.username %></p>
<% end %>

<%= link_to "View leagues", leagues_path %>