config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/user-settings', to: 'pages#user_settings', as: 'user_settings'
  # get '/user_code', to: 'games#user_code', as: 'user_code'

  devise_scope :user do
    authenticated :user do
      get '/', to: 'pages#dashboard', as: 'authenticated_root'
    end
    unauthenticated do
      get '/', to: 'pages#home', as: 'unauthenticated_root'
    end
  end

  resources :challenges, only: %i[new create]
  resources :leagues, only: %i[index new create show]

  resources :users do
    resources :games, only: %i[new create]
    resources :game_rounds, only: %i[index]
    member do
      get :send_game_invitation
      post :send_invitation
      post :accept_invitation
      delete :reject_invitation
    end
  end

  resources :games, only: %i[show edit update] do
    member do
      post :round_won
      post :update_display
      post :user_code
      post :user_ready_next_round
      post :forfeit_round
      post :invite_response
      post :cancel_invite
      post :game_disconnected
      post :game_metadata
    end
    resources :game_rounds, only: %i[new create] do
      resources :challenges, only: %i[show]
    end
  end

  resources :game_rounds, only: %i[update]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friendships_as_asker, class_name: 'Friendship', foreign_key: :asker_id, dependent: :destroy_async, inverse_of: :asker
  has_many :friendships_as_receiver, class_name: 'Friendship', foreign_key: :receiver_id, dependent: :destroy_async, inverse_of: :receiver
  has_many :games_as_player_one, class_name: 'Game', foreign_key: :player_one_id, inverse_of: :player_one
  has_many :games_as_player_two, class_name: 'Game', foreign_key: :player_two_id, inverse_of: :player_two
  has_many :game_rounds, class_name: 'GameRound', foreign_key: :winner_id, inverse_of: :winner

  has_many :user_leagues
  has_many :leagues, through: :user_leagues

  has_many :invitations
  has_many :pending_invitations, -> { where confirmed: false }, class_name: 'Invitation', foreign_key: 'friend_id', inverse_of: :user

  validates :username, presence: true, length: { maximum: 25 }

  scope :leader_board, -> { where.not(id: 1).order(score: :desc).first(10) }

  def completed_games
    games_as_player_one.or(games_as_player_two).where.not(game_winner: nil)
  end

  def latest_games
    completed_games.includes(:player_one, :player_two, :game_rounds).order(updated_at: :desc).limit(5)
  end

  def games_count
    completed_games.count
  end

  def friends
    friends_i_sent_invitation = Invitation.where(user_id: id, confirmed: true).pluck(:friend_id)
    friends_i_got_invitation = Invitation.where(friend_id: id, confirmed: true).pluck(:user_id)
    ids = friends_i_sent_invitation + friends_i_got_invitation
    User.where(id: ids)
  end

  def friend_with?(user)
    Invitation.confirmed_record?(id, user.id)
  end

  def order_friends
    friends.order(updated_at: :desc)
  end

  def send_invitation(user)
    invitations.create(friend_id: user.id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # skip_authorization only: [:send_invitation]
  def index
    @current_user = current_user
    @requests = current_user.pending_invitations
    @users = policy_scope(User)
  end

  def show
    @user = User.find(params[:id])
    @requests = current_user.pending_invitations
    @current_user = current_user
    @game = Game.new
    authorize @user
    # @friendship = current_user.friendship_with(@user)
  end

  def send_game_invitation; end

  def send_invitation
    @invitation = current_user.send_invitation(User.find(params[:id]))
    raise unless @invitation.save!

    redirect_to dashboard_path

    skip_authorization
  end

  def accept_invitation
    @invitation = Invitation.find(params[:id])
    @invitation.confirmed = true
    raise unless @invitation.save!

    redirect_to dashboard_path

    skip_authorization
  end

  def reject_invitation
    p "HERE ARE PARAMS #{params}"
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
    redirect_to dashboard_path
    skip_authorization
  end
end

app/views/users/index.html.erb
<% @users.each do |user| %>
  <% if user != current_user || user != User.find(1) %>
    <h2><%= user.username  %></h2>
    <div>
      <%= link_to "check details", user_path(user)%>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<%# Change the class names!!! %>
<div class="dashboard-wrapper"
                              data-controller="dashboard ninjaform friend"
                              data-friend-current-user-id-value="<%= current_user.id %>"
                              data-friend-player-one-ready-value="<%= false %>"
                              data-friend-player-two-ready-value="<%= false %>"
                              data-ninjaform-with-friend-value="<%= @with_friend %>">
  <div class="page-section dashboard-information user-page">
    <div class="play-box">
      <% if current_user.friend_with?(@user) %>
      <div class="friend-profile-buttons">
        <button class="btn btn-main" <%= "disabled" unless @user.online %>
              data-action="click->friend#updateGameForm click->ninjaform#withFriend" data-value="<%= @user.id %>"
              data-toggle="modal" data-target="#roundChoice">Battle</button>
        <%= link_to '<button type="button" class="btn btn-main">Unfriend</button>'.html_safe, reject_invitation_user_path(Invitation.where(user_id: @current_user.id).and(Invitation.where(friend_id: @user.id)).or(Invitation.where(user_id: @user.id).and(Invitation.where(friend_id: @current_user.id))).first.id), data: {turbo_method: :delete} %>
      </div>
      <% elsif @user == current_user %>
        <button type="button" style="font-size:20px;" class="btn btn-main">
          Settings
        </button>
      <% elsif Invitation.reacted?(current_user, @user) %>
        <p>Friend request sent, awaiting response</p>
      <% else %>
        <%= button_to "Friend +", send_invitation_user_path, data: {turbo_method: :post}, class: 'btn btn-main', style:'font-size:20px;'%>
      <% end %>
    </div>
    <div class="right-side-user-info">
      <div class="d-flex image-and-name">
        <div class="user-image">
          <%= image_tag @user.avatar, height: '80' %>
        </div>
        <h1 id="game-show-username"><%= @user.username %></h1>
      </div>
      <div class="dashboard-data-parent">
        <div class="dashboard-data">
          <h6>Score</h6>
          <span><%= @user.score %></span>
        </div>
        <div class="dashboard-data">
          <h6>Games</h6>
          <span><%= @user.games_as_player_one.where.not(game_winner: nil).count + @user.games_as_player_two.where.not(game_winner: nil).count %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-5">
    <%= link_to "Back to dashboard", dashboard_path, class: 'btn btn-second' %>
  </div>
  <%= render "shared/round_choice_modal" %>
  <%= render "shared/invite_modal" %>
  <%= render "shared/pre_game_modal" %>
  <%= render "shared/pre_game_ready_modal" %>
</div>