config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/user-settings', to: 'pages#user_settings', as: 'user_settings'
  # get '/user_code', to: 'games#user_code', as: 'user_code'

  devise_scope :user do
    authenticated :user do
      get '/', to: 'pages#dashboard', as: 'authenticated_root'
    end
    unauthenticated do
      get '/', to: 'pages#home', as: 'unauthenticated_root'
    end
  end

  resources :challenges, only: %i[new create]
  resources :leagues, only: %i[index new create show]

  resources :users do
    resources :games, only: %i[new create]
    resources :game_rounds, only: %i[index]
    member do
      get :send_game_invitation
      post :send_invitation
      post :accept_invitation
      delete :reject_invitation
    end
  end

  resources :games, only: %i[show edit update] do
    member do
      post :round_won
      post :update_display
      post :user_code
      post :user_ready_next_round
      post :forfeit_round
      post :invite_response
      post :cancel_invite
      post :game_disconnected
      post :game_metadata
    end
    resources :game_rounds, only: %i[new create] do
      resources :challenges, only: %i[show]
    end
  end

  resources :game_rounds, only: %i[update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_game_winner_modal.html.erb
<div data-game-subscription-target="gameWinnerModal" id="gameWinnerModal" class="modal fade show round-winner-modal">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content round-winner-modal-content">
      <div class="modal-header round-winner-modal-header">
        <div data-game-subscription-target="gameWinner"></div>
      </div>
      <div class="modal-body round-winner-modal-body">
        <div class="tally-container">
          <div class="page-section player-box" id="playerOneBox">
            <h6><%= @game.player_one.username %></h6>
            <p data-game-subscription-target="gameWinnerCountp1"></p>
          </div>
          <span>V</span>
          <div class="page-section player-box" id="playerTwoBox">
            <h6 data-game-subscription-target="playerTwoUsername"><%= @game.player_two.username %></h6>
            <p data-game-subscription-target="gameWinnerCountp2"></p>
          </div>
        </div>
      </div>
      <div class="modal-footer round-winner-modal-footer">
        <button data-action="click->game-subscription#endGame" class="btn btn-main">Back to Dashboard</button>
        <button data-action="click->code#showSolutionModal" class="btn btn-second">See code</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_invite_modal.html.erb
<div class="modal fade show round-winner-modal" id="inviteModal" data-friend-target="inviteModal" tabindex="-1" role="dialog" aria-labelledby="roundChoiceTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content round-choice-modal-content invite-content">
      <h3 class="invite-title" data-friend-target="inviteContent"></h3>
      <div class="button-group">
        <button class="btn btn-main" data-action="click->friend#acceptInvite">Accept</button>
        <button class="btn btn-danger" data-action="click->friend#rejectInvite">Decline</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="notifications">
  <div class="container-fluid">
    <div></div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto nav-collapsed-class">
        <% if user_signed_in? %>
          <li class="nav-item active leagues-button">
            <i class="fa-solid fa-trophy" href="/"></i>
          </li>
          <li class="nav-item active notifications-button">
            <% if current_user.pending_invitations.size > 0 %>
              <i class="fa-solid fa-bell notification" data-action="click->notifications#open">
              </i>
            <% else %>
              <i class="fa-solid fa-bell" data-action="click->notifications#open"></i>
            <% end %>
            <div class="notification-dropdown" data-notifications-target="dropdown">
              <h4>Notifications</h4>
              <ul>
                <% current_user.pending_invitations.each do |request| %>
                  <li>
                    <div class="notification-container">
                      <div class="notification-image">
                        <%= image_tag User.find(request.user_id).avatar, class: "avatar-large" %>
                      </div>
                      <div class="request-buttons">
                        <span class="invite-text"><strong><%= User.find(request.user_id).username %></strong> wants to add you as a friend.</span>
                        <div class="buttons-group">
                          <%= button_to '<i class="fa-solid fa-check"></i>'.html_safe, accept_invitation_user_path(request), data: {turbo_method: :post}, class: 'request-button btn btn-main' %>
                          <%= button_to '<i class="fa-solid fa-xmark"></i>'.html_safe, reject_invitation_user_path(request), class: 'request-button btn btn-second', data: {turbo_method: :delete} %>
                        </div>
                      </div>
                    </div>
                  </li>
                <% end %>
              </ul>
            </div>
          </li>

          <%# <li class="nav-item active">
            <i class="fa-solid fa-envelope"></i>
          </li> %>
          <li class="nav-item score-button">
             <span class="default-cursor"> <%= current_user.score %> points</span>
          </li>
          <li class="nav-item dropdown dropdown-button" data-action="click->notifications#checkModals">
            <%= image_tag "#{current_user.avatar}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown" data-notifications-target="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Settings", user_settings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item active settings-button">
            <i class="fa-solid fa-wrench"></i>
          </li>
          <li class="nav-item active logout-button">
            <%= link_to '<i class="fa-solid fa-right-from-bracket"></i>'.html_safe, destroy_user_session_path, data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</div>

app/views/shared/_player_solutions_modal.html.erb
  <div data-code-target="playerSolutionsModal" id="playerSolutionsModal" class="modal fade show round-winner-modal">
    <a class="back-button" data-action="click->code#closeSolutionModal" ><i class="fa-solid fa-arrow-left"></i> Back</a>
    <div class="modal-dialog modal-dialog-centered" role="document" id="player-solutions-second-level">
      <div class="modal-content round-winner-modal-content" id="player-solutions-third-level-content">
        <div class="round-details" id="roundOne">
          <div data-action="click->code#expandRoundOne" class="round-title-div" id="round-one-click">
            <h3 class="round-title" id="round-one-title">Round 1</h3>
          </div>
          <div class="hidden-round-details" id="round-one-hidden-details">
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_one.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_one.username %></h4>
              </div>
              <div data-code-target="roundOneEditorOne"></div>
            </div>
            <div class="round-challenge-instructions">
              <div class="user-details">
                <h4>Instructions</h4>
              </div>
              <p class="round-instructions" data-code-target='roundOneInstructions'>Content</p>
            </div>
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_two.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_two.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundOneEditorTwo"></div>
              </div>
            </div>
          </div>
        </div>
      <div class="round-details hidden" id="roundTwo">
          <div class="round-title-div" data-action="click->code#expandRoundTwo" id="round-two-click">
            <h3 class="round-title" id="round-two-title" >Round 2</h3>
          </div>
          <div class="hidden-round-details" id="round-two-hidden-details">
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_one.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_one.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundTwoEditorOne"></div>
              </div>
            </div>
            <div class="round-challenge-instructions">
              <div class="user-details">
                <h4>Instructions</h4>
              </div>
              <p data-code-target='roundTwoInstructions'>Content</p>
            </div>
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_two.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_two.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundTwoEditorTwo"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="round-details hidden" id="roundThree">
          <div class="round-title-div" data-action="click->code#expandRoundThree" id="round-three-click">
            <h3 class="round-title" id="round-three-title">Round 3</h3>
          </div>
          <div class="hidden-round-details" id="round-three-hidden-details">
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_one.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_one.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundThreeEditorOne"></div>
              </div>
            </div>
            <div class="round-challenge-instructions">
              <div class="user-details">
                <h4>Instructions</h4>
              </div>
              <p data-code-target='roundThreeInstructions'>Content</p>
            </div>
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_two.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_two.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundThreeEditorTwo"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="round-details hidden" id="roundFour">
          <div class="round-title-div" data-action="click->code#expandRoundFour" id="round-four-click">
            <h3 class="round-title" id="round-four-title">Round 4</h3>
          </div>
          <div class="hidden-round-details" id="round-four-hidden-details">
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_one.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_one.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundFourEditorOne"></div>
              </div>
            </div>
            <div class="round-challenge-instructions">
              <div class="user-details">
                <h4>Instructions</h4>
              </div>
              <p data-code-target='roundFourInstructions'>Content</p>
            </div>
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_two.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_two.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundFourEditorTwo"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="round-details hidden" id="roundFive">
          <div class="round-title-div" data-action="click->code#expandRoundFive" id="round-five-click">
            <h3 class="round-title" id="round-five-title">Round 5</h3>
          </div>
          <div class="hidden-round-details" id="round-five-hidden-details">
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_one.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_one.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundFiveEditorOne"></div>
              </div>
            </div>
            <div class="round-challenge-instructions">
              <div class="user-details">
                <h4>Instructions</h4>
              </div>
              <p data-code-target='roundFiveInstructions'>Content</p>
            </div>
            <div class="user-codebox-solutions">
              <div class="user-details">
                <div><%= image_tag(@game.player_two.avatar, class: "user-avatar-small") %></div>
                <h4 class="user-name"><%= @game.player_two.username %></h4>
              </div>
              <div class="codemirror-box">
                <div data-code-target="roundFiveEditorTwo"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_pre_game_modal.html.erb
<div data-game-subscription-target="preGameModal" data-ninjaform-target="preGameModal" data-friend-target="preGameModal" id="preGameModal" class="modal fade show round-winner-modal">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div data-game-subscription-target="preGameLoadingContent" data-friend-target="preGameLoadingContent" data-ninjaform-target="preGameLoadingContent" class="modal-content round-winner-modal-content" id="preGameLoading">
      <h1 class="typed-loading" id="typed"></h1>
      <div class="loading-animation">
        <div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
      </div>
      <button class="end-search btn btn-main" data-action="click->friend#endSearch">End Search</button>
    </div>
    <div data-game-subscription-target="playerFoundMessage" data-friend-target="playerFoundMessage" data-ninjaform-target="playerFoundMessage" id ="playerFoundMessage" class="modal-content round-winner-modal-content">
      <h1>Player Found!</h1>
    </div>
    <div data-game-subscription-target="playerRejectedInvite" data-friend-target="playerRejectedInvite" data-ninjaform-target="playerRejectedInvite" id ="playerRejectedInvite" class="modal-content round-winner-modal-content">
    </div>
    <% if @game.player_one %>
    <div data-game-subscription-target="matchDetailsAndCountdown" data-friend-target="matchDetailsAndCountdown" data-ninjaform-target="matchDetailsAndCountdown" id="matchDetailsAndCountdown" class="modal-content round-winner-modal-content">
      <div class="tally-container">
        <div class="page-section">
          <h6><%= @game.player_one.username %></h6>
          <%= image_tag(@game.player_one.avatar, class: "user-avatar") %>
        </div>
        <span>V</span>
        <div data-game-subscription-target="playerTwoUsername" class="page-section">
          <h6><%= @game.player_two.username %></h6>
          <%= image_tag(@game.player_two.avatar, class: "user-avatar", data: {'game-subscription-target' => 'playerTwoAvatar'}) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_pre_game_ready_modal.html.erb
<div data-friend-target="preGameReadyModal" id="preGameReadyModal" class="modal fade show round-winner-modal">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div data-friend-target="preGameReadyModalContent" class="modal-content round-winner-modal-content">
      <div class="modal-body round-winner-modal-body">
        <div class="tally-container">
          <div class="page-section player-box" id="player_one_box">
            <h5 data-friend-target="playerOneUsername"></h5>
            <div data-friend-target="playerOneAvatar"></div>
          </div>
          <span>V</span>
          <div class="page-section player-box" id="player_two_box">
            <h5 data-friend-target="playerTwoUsername"></h5>
            <div data-friend-target="playerTwoAvatar"></div>
          </div>
        </div>
      </div>
      <div class="modal-tickboxes">
        <h1 id="left-tick" data-friend-target="playerOneReady"></h1>
        <h1 id="right-tick" data-friend-target="playerTwoReady"></h1>
      </div>
      <div class="modal-footer round-winner-modal-footer" id="start-game-ready">
        <button data-action="click->friend#startGame" class="btn btn-second">Ready</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_round_choice_modal.html.erb
<div class="modal fade round-choice-modal" id="roundChoice" tabindex="-1" role="dialog" aria-labelledby="roundChoiceTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content round-choice-modal-content" data-ninjaform-target="roundChoiceModal">
      <div class="modal-header round-choice-modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Number of rounds</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body round-choice round-choice-modal-body">
          <%= simple_form_for [current_user, @game], :html => {:"data-ninjaform-target" => "form", :"data-friend-target" => "form"} do |f| %>
            <%= f.input :round_count, as: :radio_buttons, collection: [[1, '⚔️'], [3, "⚔️ ⚔️ ⚔️"], [5, "⚔️ ⚔️ ⚔️ ⚔️ ⚔️"]], label_method: :second, value_method: :first, label: '', class: 'form-check-inline', :input_html => { :"data-action" => "change->ninjaform#submitForm"} %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_round_winner_modal.html.erb
<div data-game-subscription-target="roundWinnerModal" id="roundWinnerModal" class="modal fade show round-winner-modal">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div data-game-subscription-target="roundWinnerModalContent" class="modal-content round-winner-modal-content">
      <div class="modal-header round-winner-modal-header">
        <div data-game-subscription-target="roundWinner"></div>
      </div>
      <div class="modal-body round-winner-modal-body">
        <div class="tally-container">
          <div class="page-section player-box" id="player_one_box">
            <h6><%= @game.player_one.username %></h6>
            <p data-game-subscription-target="roundWinnerCountp1"></p>
          </div>
          <span>V</span>
          <div class="page-section player-box" id="player_two_box">
            <h6 data-game-subscription-target="playerTwoUsername"><%= @game.player_two.username %></h6>
            <p data-game-subscription-target="roundWinnerCountp2"></p>
          </div>
        </div>
      </div>
      <div class="modal-tickboxes">
        <h1 id="left-tick" data-game-subscription-target="playerOneReady"></h1>
        <h1 id="right-tick" data-game-subscription-target="playerTwoReady"></h1>
      </div>
      <div class="modal-footer round-winner-modal-footer">
        <button data-action="click->game-subscription#nextRound" class="btn btn-second">Next Round <i class="fa-solid fa-arrow-right"></i></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar" data-controller="sidebar" data-sidebar-target="sidebar" data-action="mouseover->sidebar#open mouseout->sidebar#close">
  <%= link_to "/dashboard", class: "sidebar-logo" do %>
    <%= image_tag "logos/teki writing blank.png" %>
  <% end %>
  <div class="sidebar-lists">
    <ul class="nav-list">
      <li>
        <%= link_to leagues_path do %>
          <i class="fa-solid fa-trophy"></i>
          <span class="path_links">Leagues</span>
        <% end %>
      </li>
      <li>
        <%= link_to "/" do %>
          <i class="fa-solid fa-plus"></i>
          <span class="path_links">Submit a challenge</span>
        <% end %>
      </li>
      <li>
        <%= link_to "/" do %>
          <i class="fa-solid fa-comments"></i>
          <span class="path_links">Messages</span>
        <% end %>
      </li>
      <li>
        <%= link_to "/" do %>
          <i class="fa-solid fa-people-group"></i>
          <span class="path_links">Teki community</span>
        <% end %>
      </li>
    </ul>

    <ul class="nav-list">
      <li>
        <%= link_to "/" do %>
          <i class="fa-solid fa-book-open"></i>
          <span class="path_links">Legals</span>
        <% end %>
      </li>
      <li>
        <%= link_to "/" do %>
          <i class="fa-solid fa-phone"></i>
          <span class="path_links">Contact us</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>